export global TileLogic {
    pure callback tile_clicked(int,int);
    pure callback tile_right_clicked(int,int);
}

export struct TileData {
    revealed: bool,
    adjacent_mines: int,
    is_mine: bool,
    is_flagged: bool,
}

export component Tile inherits Window {
    in property <int> cx;
    in property <int> cy;
    in property <TileData> data;

    property <bool> long_press_timer_running: false;
    property <image> bgimg: @image-url("icon/unopened.png");
    
    width: 32px;
    height: 32px;

    TouchArea {
        pointer-event(event) => {
            // right click
            if event.button == PointerEventButton.right && event.kind == PointerEventKind.up {
                TileLogic.tile_right_clicked(cx,cy);
            }

            // (long) left-click/touch
            if event.button == PointerEventButton.left && event.kind == PointerEventKind.down {
                long_press_timer_running = true;
            }
            if event.button == PointerEventButton.left && event.kind == PointerEventKind.up {
                if long_press_timer_running == true {
                    long_press_timer_running = false;
                    TileLogic.tile_clicked(cx,cy);
                }
            }
        }

        // timer used to detect long presses
        Timer {
            interval: 400ms;
            running: long_press_timer_running;
            triggered() => {
                long_press_timer_running = false;
                TileLogic.tile_right_clicked(cx,cy);
            }
        }

        Image {
            source: 
                !data.revealed ? 
                    !data.is-flagged ? @image-url("icon/unopened.png") 
                    : @image-url("icon/flag.png")
                : data.is_mine ? @image-url("icon/boom.png")
                : data.adjacent_mines == 0 ? @image-url("icon/0.png")
                : data.adjacent_mines == 1 ? @image-url("icon/1.png")
                : data.adjacent_mines == 2 ? @image-url("icon/2.png")
                : data.adjacent_mines == 3 ? @image-url("icon/3.png")
                : data.adjacent_mines == 4 ? @image-url("icon/4.png")
                : data.adjacent_mines == 5 ? @image-url("icon/5.png")
                : data.adjacent_mines == 6 ? @image-url("icon/6.png")
                : data.adjacent_mines == 7 ? @image-url("icon/7.png")
                : @image-url("icon/8.png");
            width: parent.width;
            height: parent.height;
        }
    }
}